CREATE TYPE email_type AS ENUM ('weekly');
CREATE TABLE email_logs (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_type email_type,
    send_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX email_logs_send_at ON email_logs (send_at);
