CREATE TABLE IF NOT EXISTS users (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
    avatar VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    email_verified_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX user_email_unique ON users (email);

COMMENT ON COLUMN users.avatar IS '頭像 uri';
COMMENT ON COLUMN users.email_verified_at IS '已驗證信箱時間戳';
