CREATE TABLE IF NOT EXISTS shows (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	ticket_url TEXT,
	start_date DATE,
    end_date DATE,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	deleted_at TIMESTAMP,
	UNIQUE (ticket_url)
);

COMMENT ON COLUMN shows.ticket_url IS '售票網址';
COMMENT ON COLUMN shows.start_date IS '開演日期';
COMMENT ON COLUMN shows.end_date IS '結束日期';
