CREATE TABLE IF NOT EXISTS events (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	show_id bigint NOT NULL,
	og_image VARCHAR(255),
	og_url VARCHAR(255),
	og_title VARCHAR(255),
	og_description VARCHAR(255),
	start_date DATE,
    end_date DATE,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	deleted_at TIMESTAMP
);
