CREATE TABLE IF NOT EXISTS events (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	show_id bigint NOT NULL,
	og_image TEXT,
	og_url TEXT,
	og_title TEXT,
	og_description TEXT,
	start_date DATE,
    end_date DATE,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	deleted_at TIMESTAMP
);
