version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/
    file_exists_behavior: OVERWRITE
  - source: deployments/codeDeploy/souflair.service
    destination: /etc/systemd/system
    file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: deployments/codeDeploy/scripts/change_permissions.sh
    - location: deployments/codeDeploy/scripts/update_env.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: deployments/codeDeploy/scripts/start_app.sh
      timeout: 120
      runas: root
